export enum articleActions {
  LOAD_ARTICLES = 'LOAD_ARTICLES',
  ADD_ARTICLE = 'ADD_ARTICLE',
  REMOVE_ARTICLE = 'REMOVE_ARTICLE',
  PIN_ARTICLE = 'PIN_ARTICLE',
  LOAD_GLOBAL_ARTICLES = 'LOAD_GLOBAL_ARTICLES',
}
